### ISSUE TITLE
Colouring Componets That Are in Error State

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2697]
if user has several dozens components in wire graph, it can get hard to track down the one, that is in error state (if any of the components has faulty parameters, you cannot save the configuration, which is OK). 
I suggest that wire graph marks the components that have invalid configuration, when user is trying to save it (e.g. changing the box or text colour etc.).

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Wire graph, create a component (e.g. "timer") and enter "1,5" for the "simple.interval" parameter
3. Add other components as well - try to imagine you have a big wire graph
4. Try to save the configuration - Kura reports an error, which is OK, but the critical components are not marked in any way.

**Expected behavior**
Critical components should be marked somehow, so user will know which one are in error state.

**Screenshot:**
![Screenshot 2020-03-10 at 09 20 18](https://user-images.githubusercontent.com/15121999/76292950-767ea980-62b0-11ea-955b-ea18d2341cce.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by MMaiero** [comment]
I believe this has already been fixed in develop. @LeoNerdoG Please check

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
this is still not fiixed. Components turn into red only if user deletes a driver from Drivers list and then goes to Wire graph. Otherwise the components do not get coloured in red.

**Comment by MMaiero** [comment]
yes, that is right. But when applying, the error message now reports the component(s) with issues.

**Comment by LeoNerdoG** [comment]
I am closing due to the upper comment.
